app = "mypets-gei-api"

[env]
  JAVA_OPTS = "-XX:MaxRAM=70m"
  SERVER_FORWARD_HEADERS_STRATEGY = "NATIVE"
  SPRING_PROFILES_ACTIVE = "flyio"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
